name: Build and deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Prepare environment
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm i

      - name: Build plugins
        run: node ./build.mjs

      - name: Build 404 page
        run: |
          cp README.md dist/README.md
          printf -- "---\npermalink: /404.html\n---\n" > dist/404.md
          printf -- "> **Note:** You accessed a link that returned a 404, probably by clicking one of the plugin links. You're supposed to copy the link address and add it into Revenge/Bunny.\n\n" >> dist/404.md
          cat README.md >> dist/404.md

      # Documentation: https://github.com/peaceiris/actions-gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Makes it so the md files in the previous step get processed by GitHub Pages
          enable_jekyll: true
          # This creates the CNAME file required to host GitHub Pages on a custom domain
          # cname: example.com
            
      - name: Push up-to-date README
        continue-on-error: true
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update README"
          git push